name: Build and Publish AdNull Extension

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish to Chrome Web Store'
        required: false
        default: false
        type: boolean

jobs:
  validate:
    name: Validate Extension
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm ci --prefer-offline --no-audit
        
    - name: Validate extension
      run: npm run validate
      
    - name: Upload validation results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: validation-results-${{ github.run_id }}
        path: |
          validation-*.log
          *.json
        retention-days: 7

  build:
    name: Build Extension
    runs-on: ubuntu-latest
    needs: validate
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm ci --prefer-offline --no-audit
        
    - name: Build extension
      run: npm run build
      
    - name: Package extension
      run: npm run package
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: extension-package-${{ github.run_id }}
        path: |
          dist/
          packages/
        retention-days: 30

  test:
    name: Test Extension
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm ci --prefer-offline --no-audit
        
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: extension-package-${{ github.run_id }}
        
    - name: Run tests
      run: npm run test
      
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results-${{ github.run_id }}
        path: |
          test-results/
          coverage/
        retention-days: 7

  publish-staging:
    name: Publish to Staging
    runs-on: ubuntu-latest
    needs: [validate, build, test]
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    environment: staging
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm ci --prefer-offline --no-audit
        
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: extension-package-${{ github.run_id }}
        
    - name: Publish to staging
      env:
        CHROME_EXTENSION_ID: ${{ secrets.CHROME_EXTENSION_ID_STAGING }}
        CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
        CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
        CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
        AUTO_PUBLISH: false
      run: npm run publish

  publish-production:
    name: Publish to Production
    runs-on: ubuntu-latest
    needs: [validate, build, test]
    if: startsWith(github.ref, 'refs/tags/v') || github.event.inputs.publish == 'true'
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm ci --prefer-offline --no-audit
        
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: extension-package-${{ github.run_id }}
        
    - name: Publish to Chrome Web Store
      env:
        CHROME_EXTENSION_ID: ${{ secrets.CHROME_EXTENSION_ID }}
        CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
        CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
        CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
        AUTO_PUBLISH: ${{ github.event.inputs.publish == 'true' && 'true' || 'false' }}
      run: npm run publish
      
    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/v')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Extract version from tag
        VERSION=${GITHUB_REF#refs/tags/v}
        
        # Create release
        gh release create "v${VERSION}" \
          --title "AdNull v${VERSION}" \
          --notes "## AdNull Extension Release v${VERSION}
        
        ### Features
        - Enhanced skip strategies with multiple simultaneous methods
        - Arabic language support (تخطي, تخطى, تجاوز)
        - Multilingual support (10+ languages)
        - Real-time ad monitoring and debugging tools
        - Aggressive retry logic for stubborn ads
        - Faster detection (250ms intervals)
        
        ### Installation
        Download the extension from Chrome Web Store or install manually.
        
        ### Changelog
        See [CHANGELOG.md](CHANGELOG.md) for detailed changes." \
          packages/adnull-latest.zip

  notify:
    name: Notify Success
    runs-on: ubuntu-latest
    needs: [publish-production]
    if: always() && (needs.publish-production.result == 'success')
    
    steps:
    - name: Notify Slack
      if: ${{ secrets.SLACK_WEBHOOK_URL != '' }}
      run: |
        curl -X POST -H 'Content-type: application/json' \
        --data '{"text":"🎉 AdNull Extension v${{ github.ref_name }} published successfully to Chrome Web Store!"}' \
        ${{ secrets.SLACK_WEBHOOK_URL }}
        
    - name: Notify Discord
      if: ${{ secrets.DISCORD_WEBHOOK_URL != '' }}
      run: |
        curl -X POST -H 'Content-type: application/json' \
        --data '{"content":"🎉 AdNull Extension v${{ github.ref_name }} published successfully to Chrome Web Store!"}' \
        ${{ secrets.DISCORD_WEBHOOK_URL }} 