name: Minimal Build (No Cache)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    name: Build Extension
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        npm ci --prefer-offline --no-audit --no-fund --no-optional
        
    - name: Validate extension
      run: npm run validate
      
    - name: Build extension
      run: npm run build
      
    - name: Package extension
      run: npm run package
      
    - name: Run tests
      run: npm run test
      
    - name: List build artifacts
      run: |
        echo "Build completed successfully!"
        ls -la dist/
        ls -la packages/
        echo "Package size:"
        du -h packages/adnull-latest.zip 